version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: library-saga-orchestration-rabbitmq
    ports:
      - "5673:5672"     
      - "15673:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-saga-orchestration-sqlserver
    ports:
      - "1434:1433"      
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"