<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-Loan.Orchestrator-a071bc0b-451b-4ac1-814b-4ff439afd904</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.1" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
	</ItemGroup>
</Project>
